import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { File } from 'expo-file-system';
import { formatCurrency } from '@/lib/format';
import { periodRange } from '@/lib/dates';
import { computeGroups } from '@/lib/transactions';
import type { Period, Transaction } from '@/types';

function buildHtml(
  title: string,
  totals: { income: number; expense: number; net: number; count: number; cash: number; online: number },
  groups: ReturnType<typeof computeGroups>,
  currency: string,
): string {
  const rows = groups
    .flatMap((g) =>
      g.items.map(
        (t: Transaction) => `<tr>
        <td>${t.date}</td>
        <td>${t.reason}</td>
        <td style="text-transform:uppercase">${t.type}</td>
        <td style="text-transform:capitalize">${t.paymentMethod ?? 'cash'}</td>
        <td style="text-align:right">${formatCurrency(t.amount, currency)}</td>
      </tr>`,
      ),
    )
    .join('');

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: monospace; padding: 20px; color: #000; }
    h1 { font-size: 18px; border-bottom: 2px solid #000; padding-bottom: 6px; }
    .totals { display: flex; gap: 12px; margin: 12px 0; flex-wrap: wrap; }
    .stat { border: 1px solid #000; padding: 8px 12px; }
    .stat small { display: block; font-size: 10px; text-transform: uppercase; }
    .stat strong { font-size: 14px; }
    table { width: 100%; border-collapse: collapse; margin-top: 12px; font-size: 11px; }
    th, td { border: 1px solid #000; padding: 6px 8px; text-align: left; }
    th { background: #000; color: #fff; text-transform: uppercase; font-size: 10px; }
    .income { color: #16a34a; }
    .expense { color: #dc2626; }
    .footer { margin-top: 20px; font-size: 9px; color: #666; border-top: 1px solid #ccc; padding-top: 6px; }
  </style>
</head>
<body>
  <h1>SANA PRINTERS — ${title}</h1>
  <div class="totals">
    <div class="stat"><small>Income</small><strong class="income">${formatCurrency(totals.income, currency)}</strong></div>
    <div class="stat"><small>Expense</small><strong class="expense">${formatCurrency(totals.expense, currency)}</strong></div>
    <div class="stat"><small>Net</small><strong>${formatCurrency(totals.net, currency)}</strong></div>
    <div class="stat"><small>Cash</small><strong>${formatCurrency(totals.cash, currency)}</strong></div>
    <div class="stat"><small>Online</small><strong>${formatCurrency(totals.online, currency)}</strong></div>
    <div class="stat"><small>Transactions</small><strong>${totals.count}</strong></div>
  </div>
  <table>
    <thead><tr><th>Date</th><th>Reason</th><th>Type</th><th>Method</th><th style="text-align:right">Amount</th></tr></thead>
    <tbody>${rows || '<tr><td colspan="5" style="text-align:center">No transactions</td></tr>'}</tbody>
  </table>
  <div class="footer">Generated by Sana Printers · ${new Date().toLocaleDateString()}</div>
</body>
</html>`;
}

function buildReport(
  period: Period,
  items: Transaction[],
  currency: string,
): { title: string; html: string } {
  const groups = computeGroups(items, period);
  const totals = items.reduce(
    (acc, t) => {
      if (t.type === 'income') acc.income += t.amount;
      else acc.expense += t.amount;
      acc.count += 1;
      if (t.paymentMethod === 'cash') acc.cash += t.amount;
      else acc.online += t.amount;
      return acc;
    },
    { income: 0, expense: 0, net: 0, count: 0, cash: 0, online: 0 },
  );
  totals.net = totals.income - totals.expense;

  const range = periodRange(period);
  let title: string;
  if (period === 'today') {
    title = "Today's Report";
  } else if (period === 'weekly') {
    title = `Weekly Report (${range.start.toLocaleDateString()} – ${range.end.toLocaleDateString()})`;
  } else if (period === 'monthly') {
    title = `${range.start.toLocaleDateString(undefined, { month: 'long', year: 'numeric' })} Report`;
  } else if (period === 'yearly') {
    title = `${range.start.getFullYear()} Yearly Report`;
  } else {
    title = 'All Time Report';
  }
  return { title, html: buildHtml(title, totals, groups, currency) };
}

export async function generateReportBase64(
  period: Period,
  items: Transaction[],
  currency: string,
): Promise<string> {
  const { html } = buildReport(period, items, currency);
  const { uri } = await Print.printToFileAsync({ html, base64: false });
  const file = new File(uri);
  const buffer = await file.arrayBuffer();
  const bytes = new Uint8Array(buffer);
  let binary = '';
  for (let i = 0; i < bytes.byteLength; i++) {
    binary += String.fromCharCode(bytes[i]);
  }
  return btoa(binary);
}

export async function generateAndShareReport(
  period: Period,
  items: Transaction[],
  currency: string,
): Promise<void> {
  const { title, html } = buildReport(period, items, currency);

  const { uri } = await Print.printToFileAsync({ html, base64: false });

  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, {
      mimeType: 'application/pdf',
      dialogTitle: 'Save or share report',
    });
  }
}

function filterByMonth(items: Transaction[], year: number, month: number): Transaction[] {
  const prefix = `${year}-${String(month + 1).padStart(2, '0')}`;
  return items.filter((t) => t.date.startsWith(prefix));
}

function filterByYear(items: Transaction[], year: number): Transaction[] {
  return items.filter((t) => t.date.startsWith(`${year}-`));
}

function buildPeriodHtml(title: string, items: Transaction[], currency: string): string {
  const income = items.filter((t) => t.type === 'income').reduce((a, t) => a + t.amount, 0);
  const expense = items.filter((t) => t.type === 'expense').reduce((a, t) => a + t.amount, 0);
  const cash = items.filter((t) => t.paymentMethod === 'cash').reduce((a, t) => a + t.amount, 0);
  const online = items.filter((t) => t.paymentMethod === 'online').reduce((a, t) => a + t.amount, 0);
  const rows = items
    .map(
      (t) => `<tr>
        <td>${t.date}</td>
        <td>${t.reason}</td>
        <td style="text-transform:uppercase">${t.type}</td>
        <td style="text-transform:capitalize">${t.paymentMethod ?? 'cash'}</td>
        <td style="text-align:right">${formatCurrency(t.amount, currency)}</td>
      </tr>`,
    )
    .join('');

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: monospace; padding: 20px; color: #000; }
    h1 { font-size: 18px; border-bottom: 2px solid #000; padding-bottom: 6px; }
    .totals { display: flex; gap: 12px; margin: 12px 0; flex-wrap: wrap; }
    .stat { border: 1px solid #000; padding: 8px 12px; }
    .stat small { display: block; font-size: 10px; text-transform: uppercase; }
    .stat strong { font-size: 14px; }
    table { width: 100%; border-collapse: collapse; margin-top: 12px; font-size: 11px; }
    th, td { border: 1px solid #000; padding: 6px 8px; text-align: left; }
    th { background: #000; color: #fff; text-transform: uppercase; font-size: 10px; }
    .income { color: #16a34a; }
    .expense { color: #dc2626; }
    .footer { margin-top: 20px; font-size: 9px; color: #666; border-top: 1px solid #ccc; padding-top: 6px; }
  </style>
</head>
<body>
  <h1>SANA PRINTERS — ${title}</h1>
  <div class="totals">
    <div class="stat"><small>Income</small><strong class="income">${formatCurrency(income, currency)}</strong></div>
    <div class="stat"><small>Expense</small><strong class="expense">${formatCurrency(expense, currency)}</strong></div>
    <div class="stat"><small>Net</small><strong>${formatCurrency(income - expense, currency)}</strong></div>
    <div class="stat"><small>Cash</small><strong>${formatCurrency(cash, currency)}</strong></div>
    <div class="stat"><small>Online</small><strong>${formatCurrency(online, currency)}</strong></div>
    <div class="stat"><small>Transactions</small><strong>${items.length}</strong></div>
  </div>
  <table>
    <thead><tr><th>Date</th><th>Reason</th><th>Type</th><th>Method</th><th style="text-align:right">Amount</th></tr></thead>
    <tbody>${rows || '<tr><td colspan="5" style="text-align:center">No transactions</td></tr>'}</tbody>
  </table>
  <div class="footer">Generated by Sana Printers · ${new Date().toLocaleDateString()}</div>
</body>
</html>`;
}

export async function generateMonthPdf(year: number, month: number, items: Transaction[], currency: string): Promise<string> {
  const filtered = filterByMonth(items, year, month);
  const label = new Date(year, month, 1).toLocaleDateString(undefined, { month: 'long', year: 'numeric' });
  const title = `${label} Report`;
  const html = buildPeriodHtml(title, filtered, currency);
  const { uri } = await Print.printToFileAsync({ html, base64: false });
  const file = new File(uri);
  const buffer = await file.arrayBuffer();
  const bytes = new Uint8Array(buffer);
  let binary = '';
  for (let i = 0; i < bytes.byteLength; i++) binary += String.fromCharCode(bytes[i]);
  return btoa(binary);
}

export async function generateYearPdf(year: number, items: Transaction[], currency: string): Promise<string> {
  const filtered = filterByYear(items, year);
  const title = `${year} Yearly Report`;
  const html = buildPeriodHtml(title, filtered, currency);
  const { uri } = await Print.printToFileAsync({ html, base64: false });
  const file = new File(uri);
  const buffer = await file.arrayBuffer();
  const bytes = new Uint8Array(buffer);
  let binary = '';
  for (let i = 0; i < bytes.byteLength; i++) binary += String.fromCharCode(bytes[i]);
  return btoa(binary);
}

export async function generateCloseAccountPdf(
  items: Transaction[],
  currency: string,
  carryForward: number,
): Promise<string> {
  const income = items.filter((t) => t.type === 'income').reduce((a, t) => a + t.amount, 0);
  const expense = items.filter((t) => t.type === 'expense').reduce((a, t) => a + t.amount, 0);
  const balance = carryForward + income - expense;

  const cash = items.filter((t) => t.paymentMethod === 'cash').reduce((a, t) => a + t.amount, 0);
  const online = items.filter((t) => t.paymentMethod === 'online').reduce((a, t) => a + t.amount, 0);

  const dates = items.map((t) => t.date).sort();
  const from = dates[0] ?? new Date().toISOString().slice(0, 10);
  const to = dates[dates.length - 1] ?? new Date().toISOString().slice(0, 10);

  const rows = items
    .map(
      (t) => `<tr>
        <td>${t.date}</td>
        <td>${t.reason}</td>
        <td style="text-transform:uppercase">${t.type}</td>
        <td style="text-transform:capitalize">${t.paymentMethod ?? 'cash'}</td>
        <td style="text-align:right">${formatCurrency(t.amount, currency)}</td>
      </tr>`,
    )
    .join('');

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: monospace; padding: 20px; color: #000; }
    h1 { font-size: 18px; border-bottom: 2px solid #000; padding-bottom: 6px; }
    .totals { display: flex; gap: 12px; margin: 12px 0; flex-wrap: wrap; }
    .stat { border: 1px solid #000; padding: 8px 12px; }
    .stat small { display: block; font-size: 10px; text-transform: uppercase; }
    .stat strong { font-size: 14px; }
    table { width: 100%; border-collapse: collapse; margin-top: 12px; font-size: 11px; }
    th, td { border: 1px solid #000; padding: 6px 8px; text-align: left; }
    th { background: #000; color: #fff; text-transform: uppercase; font-size: 10px; }
    .income { color: #16a34a; }
    .expense { color: #dc2626; }
    .carry { color: #2563eb; }
    .footer { margin-top: 20px; font-size: 9px; color: #666; border-top: 1px solid #ccc; padding-top: 6px; }
  </style>
</head>
<body>
  <h1>SANA PRINTERS — Close Account (${from} to ${to})</h1>
  <div class="totals">
    <div class="stat"><small>Carry Forward</small><strong class="carry">${formatCurrency(carryForward, currency)}</strong></div>
    <div class="stat"><small>Income</small><strong class="income">${formatCurrency(income, currency)}</strong></div>
    <div class="stat"><small>Expense</small><strong class="expense">${formatCurrency(expense, currency)}</strong></div>
    <div class="stat"><small>Cash</small><strong>${formatCurrency(cash, currency)}</strong></div>
    <div class="stat"><small>Online</small><strong>${formatCurrency(online, currency)}</strong></div>
    <div class="stat"><small>Final Balance</small><strong>${formatCurrency(balance, currency)}</strong></div>
    <div class="stat"><small>Transactions</small><strong>${items.length}</strong></div>
  </div>
  <table>
    <thead><tr><th>Date</th><th>Reason</th><th>Type</th><th>Method</th><th style="text-align:right">Amount</th></tr></thead>
    <tbody>${rows || '<tr><td colspan="5" style="text-align:center">No transactions</td></tr>'}</tbody>
  </table>
  <div class="footer">Generated by Sana Printers · ${new Date().toLocaleDateString()}</div>
</body>
</html>`;

  const { uri } = await Print.printToFileAsync({ html, base64: false });
  const file = new File(uri);
  const buffer = await file.arrayBuffer();
  const bytes = new Uint8Array(buffer);
  let binary = '';
  for (let i = 0; i < bytes.byteLength; i++) binary += String.fromCharCode(bytes[i]);
  return btoa(binary);
}
