import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { File } from 'expo-file-system';
import { formatCurrency } from '@/lib/format';
import { periodRange } from '@/lib/dates';
import type { Period, Transaction } from '@/types';

const PDF_STYLE = `
  @page { margin: 15mm; }
  body { font-family: monospace; padding: 0; margin: 0; color: #000; font-size: 11px; }
  h1 { font-size: 16px; border-bottom: 2px solid #000; padding-bottom: 4px; margin: 0 0 10px 0; }
  h2 { font-size: 13px; margin: 14px 0 6px 0; padding: 4px 8px; background: #f0f0f0; border: 1px solid #000; }
  .totals { display: flex; gap: 8px; margin: 10px 0; flex-wrap: wrap; }
  .stat { border: 1px solid #000; padding: 6px 8px; }
  .stat small { display: block; font-size: 9px; text-transform: uppercase; }
  .stat strong { font-size: 12px; }
  .section { page-break-inside: avoid; }
  .section-break { page-break-before: always; padding-top: 10px; }
  table { width: 100%; border-collapse: collapse; margin-top: 6px; font-size: 10px; page-break-inside: avoid; }
  th, td { border: 1px solid #000; padding: 4px 6px; text-align: left; }
  th { background: #000; color: #fff; text-transform: uppercase; font-size: 9px; }
  .income { color: #16a34a; }
  .expense { color: #dc2626; }
  .carry { color: #2563eb; }
  .footer { margin-top: 16px; font-size: 8px; color: #666; border-top: 1px solid #ccc; padding-top: 4px; }
  .empty { text-align: center; color: #999; padding: 10px; }
`;

function buildIncomeTable(items: Transaction[], currency: string): string {
  const incomeItems = items.filter((t) => t.type === 'income');
  if (incomeItems.length === 0) return '<p class="empty">No income transactions</p>';
  const total = incomeItems.reduce((a, t) => a + t.amount, 0);
  const rows = incomeItems.map((t) => `<tr>
    <td>${t.date}</td><td>${t.reason}</td><td style="text-transform:capitalize">${t.paymentMethod ?? 'cash'}</td>
    <td style="text-align:right">${formatCurrency(t.amount, currency)}</td>
  </tr>`).join('');
  return `<table>
    <thead><tr><th>Date</th><th>Reason</th><th>Method</th><th style="text-align:right">Amount</th></tr></thead>
    <tbody>${rows}<tr style="font-weight:bold"><td colspan="3">Total Income</td><td style="text-align:right" class="income">${formatCurrency(total, currency)}</td></tr></tbody>
  </table>`;
}

function buildExpenseTable(items: Transaction[], currency: string): string {
  const expenseItems = items.filter((t) => t.type === 'expense');
  if (expenseItems.length === 0) return '<p class="empty">No expense transactions</p>';
  const total = expenseItems.reduce((a, t) => a + t.amount, 0);
  const rows = expenseItems.map((t) => `<tr>
    <td>${t.date}</td><td>${t.reason}</td><td style="text-transform:capitalize">${t.paymentMethod ?? 'cash'}</td>
    <td style="text-align:right">${formatCurrency(t.amount, currency)}</td>
  </tr>`).join('');
  return `<table>
    <thead><tr><th>Date</th><th>Reason</th><th>Method</th><th style="text-align:right">Amount</th></tr></thead>
    <tbody>${rows}<tr style="font-weight:bold"><td colspan="3">Total Expense</td><td style="text-align:right" class="expense">${formatCurrency(total, currency)}</td></tr></tbody>
  </table>`;
}

function buildSummaryTotals(
  items: Transaction[],
  currency: string,
  extra?: { label: string; value: string; cls?: string }[],
): string {
  const income = items.filter((t) => t.type === 'income').reduce((a, t) => a + t.amount, 0);
  const expense = items.filter((t) => t.type === 'expense').reduce((a, t) => a + t.amount, 0);
  const cash = items.filter((t) => t.paymentMethod === 'cash').reduce((a, t) => a + t.amount, 0);
  const online = items.filter((t) => t.paymentMethod === 'online').reduce((a, t) => a + t.amount, 0);
  const stats = [
    { label: 'Income', value: formatCurrency(income, currency), cls: 'income' },
    { label: 'Expense', value: formatCurrency(expense, currency), cls: 'expense' },
    { label: 'Net', value: formatCurrency(income - expense, currency) },
    { label: 'Cash', value: formatCurrency(cash, currency) },
    { label: 'Online', value: formatCurrency(online, currency) },
    { label: 'Transactions', value: String(items.length) },
    ...(extra ?? []),
  ];
  return `<div class="totals">${stats.map((s) =>
    `<div class="stat"><small>${s.label}</small><strong${s.cls ? ` class="${s.cls}"` : ''}>${s.value}</strong></div>`
  ).join('')}</div>`;
}

function buildReportHtml(title: string, items: Transaction[], currency: string, footer?: string): string {
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><style>${PDF_STYLE}</style></head><body>
  <h1>SANA PRINTERS — ${title}</h1>
  ${buildSummaryTotals(items, currency)}
  <div class="section"><h2>Income</h2>${buildIncomeTable(items, currency)}</div>
  <div class="section-break"><h2>Expense</h2>${buildExpenseTable(items, currency)}</div>
  <div class="footer">${footer ?? 'Generated by Sana Printers'} · ${new Date().toLocaleDateString()}</div>
</body></html>`;
}

function buildReport(
  period: Period,
  items: Transaction[],
  currency: string,
): { title: string; html: string } {
  const range = periodRange(period);
  let title: string;
  if (period === 'today') {
    title = "Today's Report";
  } else if (period === 'weekly') {
    title = `Weekly Report (${range.start.toLocaleDateString()} – ${range.end.toLocaleDateString()})`;
  } else if (period === 'monthly') {
    title = `${range.start.toLocaleDateString(undefined, { month: 'long', year: 'numeric' })} Report`;
  } else if (period === 'yearly') {
    title = `${range.start.getFullYear()} Yearly Report`;
  } else {
    title = 'All Time Report';
  }
  return { title, html: buildReportHtml(title, items, currency) };
}

export async function generateReportBase64(
  period: Period,
  items: Transaction[],
  currency: string,
): Promise<string> {
  const { html } = buildReport(period, items, currency);
  const { uri } = await Print.printToFileAsync({ html, base64: false });
  const file = new File(uri);
  const buffer = await file.arrayBuffer();
  const bytes = new Uint8Array(buffer);
  let binary = '';
  for (let i = 0; i < bytes.byteLength; i++) {
    binary += String.fromCharCode(bytes[i]);
  }
  return btoa(binary);
}

export async function generateAndShareReport(
  period: Period,
  items: Transaction[],
  currency: string,
): Promise<void> {
  const { title, html } = buildReport(period, items, currency);

  const { uri } = await Print.printToFileAsync({ html, base64: false });

  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, {
      mimeType: 'application/pdf',
      dialogTitle: 'Save or share report',
    });
  }
}

function filterByMonth(items: Transaction[], year: number, month: number): Transaction[] {
  const prefix = `${year}-${String(month + 1).padStart(2, '0')}`;
  return items.filter((t) => t.date.startsWith(prefix));
}

function filterByYear(items: Transaction[], year: number): Transaction[] {
  return items.filter((t) => t.date.startsWith(`${year}-`));
}

export async function generateMonthPdf(year: number, month: number, items: Transaction[], currency: string): Promise<string> {
  const filtered = filterByMonth(items, year, month);
  const label = new Date(year, month, 1).toLocaleDateString(undefined, { month: 'long', year: 'numeric' });
  const title = `${label} Report`;
  const html = buildReportHtml(title, filtered, currency);
  const { uri } = await Print.printToFileAsync({ html, base64: false });
  const file = new File(uri);
  const buffer = await file.arrayBuffer();
  const bytes = new Uint8Array(buffer);
  let binary = '';
  for (let i = 0; i < bytes.byteLength; i++) binary += String.fromCharCode(bytes[i]);
  return btoa(binary);
}

export async function generateYearPdf(year: number, items: Transaction[], currency: string): Promise<string> {
  const filtered = filterByYear(items, year);
  const title = `${year} Yearly Report`;
  const html = buildReportHtml(title, filtered, currency);
  const { uri } = await Print.printToFileAsync({ html, base64: false });
  const file = new File(uri);
  const buffer = await file.arrayBuffer();
  const bytes = new Uint8Array(buffer);
  let binary = '';
  for (let i = 0; i < bytes.byteLength; i++) binary += String.fromCharCode(bytes[i]);
  return btoa(binary);
}

export async function generateCloseAccountPdf(
  items: Transaction[],
  currency: string,
  carryForward: number,
): Promise<string> {
  const income = items.filter((t) => t.type === 'income').reduce((a, t) => a + t.amount, 0);
  const expense = items.filter((t) => t.type === 'expense').reduce((a, t) => a + t.amount, 0);
  const balance = carryForward + income - expense;
  const dates = items.map((t) => t.date).sort();
  const from = dates[0] ?? new Date().toISOString().slice(0, 10);
  const to = dates[dates.length - 1] ?? new Date().toISOString().slice(0, 10);

  const incomeItems = items.filter((t) => t.type === 'income');
  const expenseItems = items.filter((t) => t.type === 'expense');
  const incTotal = incomeItems.reduce((a, t) => a + t.amount, 0);
  const expTotal = expenseItems.reduce((a, t) => a + t.amount, 0);

  const incRows = incomeItems.map((t) => `<tr><td>${t.date}</td><td>${t.reason}</td><td style="text-transform:capitalize">${t.paymentMethod ?? 'cash'}</td><td style="text-align:right">${formatCurrency(t.amount, currency)}</td></tr>`).join('');
  const expRows = expenseItems.map((t) => `<tr><td>${t.date}</td><td>${t.reason}</td><td style="text-transform:capitalize">${t.paymentMethod ?? 'cash'}</td><td style="text-align:right">${formatCurrency(t.amount, currency)}</td></tr>`).join('');

  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><style>${PDF_STYLE}</style></head><body>
  <h1>SANA PRINTERS — Close Account (${from} to ${to})</h1>
  ${buildSummaryTotals(items, currency, [
    { label: 'Carry Forward', value: formatCurrency(carryForward, currency), cls: 'carry' },
    { label: 'Final Balance', value: formatCurrency(balance, currency) },
  ])}
  <div class="section"><h2>Income</h2>
    <table><thead><tr><th>Date</th><th>Reason</th><th>Method</th><th style="text-align:right">Amount</th></tr></thead>
    <tbody>${incRows || '<tr><td colspan="4" class="empty">No income</td></tr>'}
    <tr style="font-weight:bold"><td colspan="3">Total Income</td><td style="text-align:right" class="income">${formatCurrency(incTotal, currency)}</td></tr></tbody></table>
  </div>
  <div class="section-break"><h2>Expense</h2>
    <table><thead><tr><th>Date</th><th>Reason</th><th>Method</th><th style="text-align:right">Amount</th></tr></thead>
    <tbody>${expRows || '<tr><td colspan="4" class="empty">No expense</td></tr>'}
    <tr style="font-weight:bold"><td colspan="3">Total Expense</td><td style="text-align:right" class="expense">${formatCurrency(expTotal, currency)}</td></tr></tbody></table>
  </div>
  <div class="footer">Generated by Sana Printers · ${new Date().toLocaleDateString()}</div>
</body></html>`;

  const { uri } = await Print.printToFileAsync({ html, base64: false });
  const file = new File(uri);
  const buffer = await file.arrayBuffer();
  const bytes = new Uint8Array(buffer);
  let binary = '';
  for (let i = 0; i < bytes.byteLength; i++) binary += String.fromCharCode(bytes[i]);
  return btoa(binary);
}
